<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="qualified" targetNamespace="https://schema.ccmm.cz/research-data/1.2" xmlns:ccmm="https://schema.ccmm.cz/research-data/1.2" xmlns:sawsdl="http://www.w3.org/ns/sawsdl">
  <xs:complexType name="iso_5181_json_representation" sawsdl:modelReference="https://model.ccmm.cz/vocabulary/ccmm#Iso5181JsonRepresentation">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        ISO 5181 JSON representation - Provides link to  the representation of provenance activity information in JSON format according to the ISO/IEC 5181 standard about data provenance.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="iri" type="xs:anyURI"/>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" namespace="##other"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="iso_5181_json_representation" type="ccmm:iso_5181_json_representation"/>
</xs:schema>
